:Author: testing223
:Email:
:Date: 03/01/2024
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── Untitled_2_jan03a   => Arduno file  
  ├── layout.png          => ------------------
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| 1 | LI-PO battry    | VIN         | 1       
| 2 | 4 channel relay |             | 1        
| 3 | -VCC            | 3v3         | 1     
| 4 | GND             | GND         | 1       
| 5 | IN1             | D13         | 1        
| 6 | IN2             | D12         | 1   
| 7 | IN3             | D27         | 1       
| 8 | IN4             | D26         | 1             
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
