// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0e884359-0808-4bc9-af41-6176cffc8e5b";

const char SSID[]               = "";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "k?xWzC8gTOCAgYZFq5TQifHNN";    // Secret device password

void onNo1Change();
void onNo2Change();
void onNo3Change();
void onNo4Change();

CloudLight no1;
CloudLight no2;
CloudLight no3;
CloudLight no4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(no1, READWRITE, ON_CHANGE, onNo1Change);
  ArduinoCloud.addProperty(no2, READWRITE, ON_CHANGE, onNo2Change);
  ArduinoCloud.addProperty(no3, READWRITE, ON_CHANGE, onNo3Change);
  ArduinoCloud.addProperty(no4, READWRITE, ON_CHANGE, onNo4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
